server:
  servlet:
    context-path: /tour-api
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: tour-api
  messages:
    basename: bundles/apiLanguageBundle
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
